Override some versions needed to get buildout to run:
The constraint, 1.3.2, is not consistent with the requirement,
'plone.app.jquerytools>=1.5.1'.
While:
  Installing.
  Getting section zeo.
  Initializing part zeo.
Traceback (most recent call last):
  File "/opt/src/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/buildout.py",
line 1866, in main
    getattr(buildout, command)(args)
  File "/opt/src/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/buildout.py",
line 509, in install
    [self[part]['recipe'] for part in install_parts]
  File "/opt/src/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/buildout.py",
line 1104, in __getitem__
    options._initialize()
  File "/opt/src/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/buildout.py",
line 1192, in _initialize
    self.recipe = recipe_class(buildout, name, self)
  File "/opt/src/eggs/plone.recipe.zeoserver-1.2.6-py2.7.egg/plone/recipe/zeoserver/__init__.py",
line 34, in __init__
    _, self.zodb_ws = self.egg.working_set()
  File "/opt/src/eggs/zc.recipe.egg-1.3.2-py2.7.egg/zc/recipe/egg/egg.py",
line 101, in working_set
    **kw)
  File "/opt/src/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/easy_install.py",
line 1079, in install
    return installer.install(specs, working_set)
  File "/opt/src/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/easy_install.py",
line 905, in install
    req = self._constrain(requirements.pop(0))
  File "/opt/src/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/easy_install.py",
line 861, in _constrain
    requirement = _constrained_requirement(constraint, requirement)
  File "/opt/src/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/easy_install.py",
line 1910, in _constrained_requirement
    _constrained_requirement_constraint(constraint, requirement)
  File "/opt/src/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/easy_install.py",
line 1951, in _constrained_requirement_constraint
    bad_constraint(constraint, requirement)
  File "/opt/src/eggs/zc.buildout-1.7.1-py2.7.egg/zc/buildout/easy_install.py",
line 1923, in bad_constraint
    raise IncompatibleConstraintError("Bad constraint", constraint, requirement)
IncompatibleConstraintError: Bad constraint 1.3.2 plone.app.jquerytools>=1.5.1

I didn't have time to look into where the 'plone.app.jquerytools>=1.5.1' is
coming from so I'm not sure this is the right solution.